# Generated by Django 3.1.4 on 2020-12-12 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название элемента')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_done', models.BooleanField(default=False)),
                ('expare_date', models.DateTimeField(blank=True)),
                ('listmodel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.listmodel')),
            ],
            options={
                'verbose_name': 'Элементы',
                'verbose_name_plural': 'Элементы',
                'unique_together': {('name', 'listmodel_id')},
            },
        ),
    ]
