# Generated by Django 3.1.4 on 2020-12-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('todo_item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmodel',
            old_name='expare_date',
            new_name='expr_date',
        ),
        migrations.RenameField(
            model_name='itemmodel',
            old_name='listmodel_id',
            new_name='listmodules_id',
        ),
        migrations.AlterUniqueTogether(
            name='itemmodel',
            unique_together={('name', 'listmodules_id')},
        ),
    ]
