# Generated by Django 3.1.4 on 2020-12-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_item', '0003_auto_20201222_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmodel',
            old_name='listmodules_id',
            new_name='listmodules',
        ),
    ]
