# Generated by Django 3.1.4 on 2020-12-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_item', '0004_auto_20201222_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='expr_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
